### ISSUE TITLE
C++ variant

### ISSUE THREAD

**Issue by FinnT730** [SasLuca/raylib-cmake-template#1]
Hi, I wanted to know how I could make this work with C++.
Currently it is using C, but I want to use some things from C++ as well.
Unless there are ways to get C++ things working that I don't know about, I would love this.

Thanks in advance!

**Comment by SasLuca** [comment]
Hi, It's quite easy to make it work with C++, you just have to change main.c to main.cpp and the following lines in CMakelists.txt from:

```
project(raylib_template C)

set(CMAKE_C_STANDARD 99)

add_executable(raylib_template src/main.c)
```

to

```
project(raylib_template CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(raylib_template src/main.cpp)
```

Maybe I can add this to the readme.

**Comment by FinnT730** [comment]
Hi, thanks for coming back so quickly!
Yeah, this seems to work, thank you! I could not figure this out for some reason (Cmake is not my strong suit.)

Thank you for this :)
Have an nice day.
