### ISSUE TITLE
Using this template with Cmake Doesnt work

### ISSUE THREAD

**Issue by brammie15** [SasLuca/raylib-cmake-template#2]
I found out using this template (atleast with Clion in my case) the C++ version breaks Cmake cuz its failing to compile Raylib as c++ or smthing 

Anyways if you swap `project(raylib_template CXX)` with `project(raylib_template C CXX)`

it works (btw could be due to my peticular setup but who knows)

**Comment by SasLuca** [comment]
I think you might be correct on this, I recently had someone complain that they had issues with it. I will make this change and test, it's kinda weird tho because on my setup it worked but maybe it depends on compiler&platform mix.

**Comment by SasLuca** [comment]
Fixed

https://github.com/SasLuca/raylib-cpp-cmake-template/commit/90c7e03b6b9c4766d165bbec0998aa27a3ddeacc
