### ISSUE TITLE
This repository does not have a license

### ISSUE THREAD

**Issue by Kazuo256** [SasLuca/raylib-cmake-template#7]
To avoid copyright problems and ensure that the community can use the source code here freely, would it be possible to add a free software license? The zlib license, used by raylib itself, would fit nicely since the CMake ends up downloading it, and will not prevent people from closing their game's source as needed.

**Comment by SasLuca** [comment]
Sure thing, I wasn't under the impression that a github template needs one but I suppose it can make sense.

**Comment by SasLuca** [comment]
For the zlib license I see I need to add a name like `Copyright (c) 2013-2023 Ramon Santamaria (@raysan5)`. Should I just add mine?

**Comment by Kazuo256** [comment]
> For the zlib license I see I need to add a name like `Copyright (c) 2013-2023 Ramon Santamaria (@raysan5)`. Should I just add mine?

Yup, since you are the copyright owner of this code.

**Comment by SasLuca** [comment]
Done https://github.com/SasLuca/raylib-cmake-template/commit/666ce821967301224df09cc0991877c09ce87222

**Comment by Kazuo256** [comment]
> Sure thing, I wasn't under the impression that a github template needs one but I suppose it can make sense.

Even more so for being a template, because it is literally meant to be studied, copied, modified, then redistributed (which are the operations covered by free software licenses).

**Comment by Kazuo256** [comment]
> Done [666ce82](https://github.com/SasLuca/raylib-cmake-template/commit/666ce821967301224df09cc0991877c09ce87222)

Thank you! =D
